### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by liveinno** [spuf/tor-with-auth#10]
Добрый день
Для новичков нет документации? Запустил еле как, но при попытке соединения пишет ошибку. Видимо пропускаю входные аргументы. Буду благодарен, спасибо

**Comment by spuf** [comment]
Для новичков не будет документации.

Могу только поделиться `docker-compose.yml`:
```yml
version: '2'
services:
  tor-with-auth:		
    image: spuf/tor-with-auth:latest		
    restart: unless-stopped		
    ports:		
      - "1080:1080"		
    environment:		
      TOR_ExcludeExitNodes: "{ua},{ru},{by},{kz},{tm},{cn},{ir}"		
      PROXY_USER: "username"		
      PROXY_PASSWORD: "password"		
    volumes:		
      - "tor-data:/var/lib/tor"		
```
